skip-check:
  - CKV_K8S_35    # Prefer using secrets as files over secrets as environment variables
  - CKV_K8S_43    # Image should use digest
  - CKV_K8S_40    # Containers should run as a high UID to avoid host conflict (unprivileged nginx runs as user 101)
  - CKV_K8S_22    # Use read-only filesystem for containers where possible - tomcat unwrapps the .war file at startup therefore readonly isn't possible
