apiVersion: v2
name: mailpit
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: mailpit
    version: 0.34.1
    repository: https://jouve.github.io/charts/
