apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zi-staging
nameSuffix: -staging

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: github-runner
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: LABELS
        value: "k8s,staging"