# deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zurimpact-backend
spec:
  template:
    spec:
      containers:
      - name: zurimpact-backend
        env:
        - name: DB_URL
          value: jdbc:postgresql://postgres-zi-staging:5432/zurimpact
        - name: SPRING_MAIL_HOST
          value: "mailpit-staging-smtp"
        - name: APP_BASE_URL
          value: "https://zurimpact-staging.pm4.init-lab.ch"
