apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zi-staging

resources:
- ../../base

images:
- name: ghcr.io/zurimpact/zurimpact-backend
  newTag: dev-2b176e9
- name: ghcr.io/zurimpact/zurimpact-frontend
  newTag: dev-2b176e9

patches:
- path: deployment-patch.yaml

- target:
    kind: Ingress
    name: zurimpact-frontend
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: zurimpact-staging.pm4.init-lab.ch
