apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zi-prod

resources:
- ../../base

images:
- name: ghcr.io/zurimpact/zurimpact-backend
  newTag: v0.1.2
- name: ghcr.io/zurimpact/zurimpact-frontend
  newTag: v0.1.2

patches:
- path: deployment-patch.yaml

- target:
    kind: Ingress
    name: zurimpact-frontend
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: zurimpact.pm4.init-lab.ch
