postgres:
  image:
    pullPolicy: Always
  initResources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    className: cinder-csi
    requestedSize: "5Gi"
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  settings:
    existingSecret: postgres-admin-secret
    superuser:
      secretKey: "POSTGRES_USER"
    superuserPassword:
      secretKey: "POSTGRES_PASSWORD"
  podSecurityContext:
    fsGroup: 999
    supplementalGroups:
    - 999
    seccompProfile:
      type: RuntimeDefault
  userDatabase:
    existingSecret: postgres-user-secret
    name:
      secretKey: POSTGRES_DB
    user:
      secretKey: POSTGRES_USER
    password:
      secretKey: POSTGRES_PASSWORD
